### ISSUE TITLE
Error with `visitBackspaceStatement` when importing a project with a file containing a `BACKSPACE (..)` Statement

### ISSUE THREAD

**Issue by uNouss** [moosetechnology/Esope#167]
Given a project (see the structure below to reproduce)
```
myproject
├── inc
└── src
    └── toto.f
```

and a file `toto.f` that contains this source code

```f77
      PROGRAM toto
      BACKSPACE (6)
      END
```
When importing the project we encountered a problem (see screenshot) with the `BACKSPACE (..)` statement.

This led to the `visitList` selector, where you shouldn't end up.

```st
src := '/tmp/myproject/src'.
inc := '/tmp/myproject/inc'.

importer := FortranProjectImporter new
    sourceFolder: src ;
    includeFolder: inc ;
    stopOnError: false ;
    withSanityChecks: true ;
    defaultFileEncoding: 'utf8' ;
    yourself.

model := importer import.
```

![image](https://github.com/moosetechnology/Esope/assets/15982321/8fd17c0d-ce99-4e92-bd04-a5135d318ad1)

**Comment by NicolasAnquetil** [comment]
no error for me with that example
